[build]
  publish = "dist"
  command = "gridsome build"

[context.production]
  environment = { YARN_VERSION = "1.22.17", NODE_VERSION = "16.13.2" }

[[redirects]]
  from = "http://tonyjunkes.com/*"
  to = "https://tonyjunkes.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://tonyjunkes.netlify.com/*"
  to = "https://tonyjunkes.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://tonyjunkes.dev/*"
  to = "https://tonyjunkes.com/:splat"
  status = 302
  force = true

[[redirects]]
  from = "http://tonyjunkes.dev/*"
  to = "https://tonyjunkes.com/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/feeds/rss"
  to = "/rss.xml"
  status = 301

[[redirects]]
  from = "/blog/page/*"
  to = "/blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/tags/*"
  to = "/tag/:splat"
  status = 301
  force = true
